### ISSUE TITLE
Feedback 10.10.3

### ISSUE THREAD

**Issue by corxit** [AustinSMU/PRECISION-M3800-OSX#2]
Hi AustinSMU,
It’s incredible that you reply and update the project so quickly! Thanks for you patient! Cause of some strange case, I need to reload the system. Then I discovered your new addition, you can imagine how surprised I am.  I have followed again your guid. I would like to consign you some little omissions in my processing:

<h5>Post installation</h5>

<blockquote> The command below can’t go on, so I changed it to be cd ~/PRECIS... 
<br> cd /PRECISION-M3800-OSX
<br>The ./DELLM3800.sh goes on strike, like this: 
line 230: syntax error near unexpected token... it just missed these two little guys " ;; "</blockquote>

As for the problem login to the Appstore, I’m sorry that I can’t solve it  yet with out that two Kexts, maybe I missed some steps because I’m not  enough patient this time...

**Comment by AustinSMU** [comment]
Haha, well I've got to stay bleeding edge! I have a feeling your Bluetooth connection has stolen the eth0 spot before your Ethernet connection got a chance. Try the following to resolve your App Store connection issue:
1. Open System Preferences > Network
2. Delete all entries under 'Location' that you can, leaving only the current profile.
3. Delete all network interfaces (Ethernet, Bluetooth, etc.) using the '-' button
4. Click 'Apply' to save the changes.
5. Using Finder, navigate to Library/Preferences/SystemConfiguration and delete 'NetworkInterfaces.plist' or use a command such as sudo rm /Library/Preferences/SystemConfiguration/NetworkInterfaces.plist
6. Reboot.
7. Reopen System Preferences > Network
8. Add your Ethernet connection first.
9. Click apply.
10. Verify your Ethernet connection is 'eth0' under Utilities > System Information > Network

Thanks for catching the missing ;; as well, I've updated the script accordingly. Let me know if the above fix works for you.

**Comment by ghost** [comment]
Hi AustinSMU，
 Thanks for this awesome tut .

I build the usb booting driver follows "Installation" Chapter and It works great.

I follow the steps but it dosen't works . when I reboot my laptop , it stuck at "white apple logo" loading .
where can I find out logs ?

And I was confused in "Post Installation" Chapter .

"
Mount your EFI partition, and copy your ACPI tables to the DSDT/raw folder:
 sudo mkdir /Volumes/EFI 
 sudo mount -t msdos /dev/disk0s1 /Volumes/EFI 
 git clone http://www.github.com/AustinSMU/PRECISION-M3800-OSX 
 sudo cp /Volumes/EFI/EFI/CLOVER/ACPI/origin/DSDT.aml ~/PRECISION-M3800-OSX/DSDT/raw/ 
 sudo cp /Volumes/EFI/EFI/CLOVER/ACPI/origin/SSDT\* ~/PRECISION-M3800-OSX/DSDT/raw/ 
 sudo umount /dev/disk0s1  
"

is this " EFI partition"  meant the "the USB drive of Clover" mentioned  above ?

"
Replace the CLOVER folder in your EFI with the one located in your clone of my repository, and then copy the patched tables from the DSDT/compiled folder to the EFI/CLOVER/ACPI/patched folder on your EFI:
"
and this "CLOVER" folder is the hidden partition of the ssd drive ?

Another question is  
" Can I run the script  offline" ? Because I have no any other  wifi card or usb wifi card to use .

Clover_v2.3k_r3193
commandlinetoolsosx10.10forxcode6.3
OSX 10.10.2[MAS]14C109 

thanks.

**Comment by AustinSMU** [comment]
d"is this " EFI partition" meant the "the USB drive of Clover" mentioned above ?"
-No, this is a reference to your EFI System Partition (commonly referred to as EFI or ESP), the hidden first partition on a GPT-formatted disk. You can view this partition by issuing the following commands in terminal:
sudo mkdir /Volumes/EFI
sudo mount -t msdos /dev/disk0s1 /Volumes/EFI
If you are unable to mount this partition, it is likely your disk was converted to CoreStorage during the installation process, which prevents the FAT32 driver loading at startup to mount the partition. See the  instructions for verifying and reverting CoreStorage in the post-installation chapter.

"and this "CLOVER" folder is the hidden partition of the ssd drive ?"
-If you followed the instructions correctly, after installing Clover with the selected options, you will have a CLOVER folder on the aforementioned EFI System Partition, which needs to be replaced with the one from my repository.

You can run the script on an offline machine if you download the repository and run the update command on an alternative machine with an internet connection beforehand.

You can download and install Clover Configurator or DPCI Manager to view your Clover boot logs. These would be helpful for me to troubleshoot your issue faster.

**Comment by ghost** [comment]
hello AustinSMU ,

I install osx 10.10.2 fresh follow your steps again .But when after run all ./DELLM3800.sh patch steps , I reboot and boot osx through the CLOVER in "EFI System Partition", but It stuck at "white apple logo" loading again.

I found some logs In  /Library/Logs/CloverEFI ,but there were no errors in it .
Can you help me to find out  anything wrong ? 

the logs and DSDT files  are in this url 

https://mega.co.nz/#!35ZinRzK!4BzSZTGBBbo3hGAj8w5W4xRJgjvEGpBgHYi_QLI_cw4

thanks .

**Comment by ghost** [comment]
and there is a error  in  file 

PRECISION-M3800-OSX/clover/config.plist

line 126  , it should be  <string>\EFI\CLOVER\tools\SHELL2.efi</string>

**Comment by AustinSMU** [comment]
Try removing the FakePCIID and FakePCIIDIntelHD4600 kexts, and changing the ig-platform-id in the config.plist to 0x0a2e0008 instead of 0x0a260006. I've added a "CLOVER-ALT" folder to the repository with these changes, along with a modified frame buffer kext patch. Rerun the update command to sync, delete the contents of the CLOVER folder on your EFI, and add the contents of CLOVER-ALT. This is the original configuration for 10.10.0-10.10.1, which seems to resolve issues for systems not booting to desktop with FakePCIID and the 0x0a260006 platform ID.

*\* Edit - I have replaced the original clover folder with the updated fixes using the 0x0a2e0008/non-FakePCIID/96mb fb method. Note re-patch your ACPI tables using the script - there is an extra DSDT patch needed to fix PNOT/PPNT when discarding FakePCIID. *\*

**Comment by AustinSMU** [comment]
I've also corrected the ...\tools\SHELL2.efi typo, thank you again for the feedback. Please continue posting any errors in path names that you find, and if the above fixes resolve your graphics issues.

**Comment by AustinSMU** [comment]
Also gdhsn -

I have reviewed your clover boot log.

0:100  0:000  Found Plist String = , parse XML in LoadOptions
0:100  0:000  Xml in load options is bad

At least part of your config.plist is corrupt. Build a new one using RehabMan's IntelHD4600 as a template.

6:430  0:000  Inserting SSDT-0.AML from EFI\CLOVER\ACPI\patched ... Success
6:431  0:000  Inserting SSDT-1.AML from EFI\CLOVER\ACPI\patched ... Success
6:431  0:000  Inserting SSDT-10.AML from EFI\CLOVER\ACPI\patched ... Success
6:432  0:001  Inserting SSDT-11.AML from EFI\CLOVER\ACPI\patched ... Success
6:433  0:000  Inserting SSDT-12.AML from EFI\CLOVER\ACPI\patched ... Success
6:433  0:000  Inserting SSDT-13.AML from EFI\CLOVER\ACPI\patched ... Success
6:434  0:000  Inserting SSDT-14.AML from EFI\CLOVER\ACPI\patched ... Success
6:435  0:000  Inserting SSDT-15.AML from EFI\CLOVER\ACPI\patched ... Success
6:435  0:000  Inserting SSDT-2.AML from EFI\CLOVER\ACPI\patched ... Success
6:436  0:000  Inserting SSDT-3.AML from EFI\CLOVER\ACPI\patched ... Success
6:436  0:000  Inserting SSDT-7.AML from EFI\CLOVER\ACPI\patched ... Success
6:437  0:000  Inserting SSDT-8.AML from EFI\CLOVER\ACPI\patched ... Success
6:437  0:000  Inserting SSDT-9.AML from EFI\CLOVER\ACPI\patched ... Success
6:438  0:000  Inserting SSDT-pr.aml from EFI\CLOVER\ACPI\patched ... Success
6:438  0:000  Inserting SSDT-rmne.aml from EFI\CLOVER\ACPI\patched ... Success

For some reason, your ACPI tables are loading out-of-order, rather than the Clover "SortOrder". You could try removing the SortOrder flag in the config.plist, changing the flag name to SortedOrder or renumbering your tables to see if the order is corrected. It would seem renumbering tables 2-15 to 02,03,etc.,15 might yield the desirable order. The SortOrder scheme should follow 1,2,3,etc., but I could have easily missed that update in the changelog if it was tweaked in the last several revisions.

0:622  0:000    PciRoot(0x0)\Pci(0x1F,0x2)\Sata(0x0,0xFFFF,0x0)\HD(4,GPT,65623C7E-D8E7-4428-A212-58A8AE53D334,0x42C9800,0xABB2000)
0:623  0:000    Result of bootcode detection: bootable Windows (vista,win)

It looks like you have an instance of Windows running on your HDD. Did you perform the instructions on a clean drive partitioned by OS X Disk Utility? You should only have 3 GPT partitions after a clean installation - the EFI System Partition, your OS X Installation, and a Recovery HD partition.

**Comment by ghost** [comment]
Hi AustinSMU ,
It still not work properly, I may go to learn some background knowledge about "how to hack osx on PC".
And I will feekback immediately when I got some progress.
thank you very much .

**Comment by AustinSMU** [comment]
That's unnecessary really. You will have to elaborate considerably on what exactly is occurring so that I can advise you to the appropriate fix. If you have the 3200x1800 model, there are literally only two hardware components that could potentially prevent our systems from being identical (Three if you count my wifi card swap), and these potential differences have a negligible impact on graphics support.

**Comment by nzp2** [comment]
Hi Austin SMU,I've followed the tips,but got stuck here"1.Unlocking the BIOS-9.Open a command prompt with administrative rights and execute: afuwinx64 bios_patched.bin /GAN".It shows "Error:Secure Flash Rom Verify fail".And then nothing changed.I'll really appreciate that if you could tell how to fix it.

**Comment by AustinSMU** [comment]
I'm afraid I haven't had anyone report that error before, nor seen it myself. I suspect you might have missed a minor detail in the instructions, so my first recommendation would be to repeat the procedure from scratch if you haven't done so already. You might try running the command without /GAN, or alternatively with /AN. If I recall correctly, running the afuwinx64 command without any arguments will display all the available command syntax. I will try to skim the revision documentation for new command syntax when I get some time over the next few days.

**Comment by nzp2** [comment]
Thanks a lot.Finally fix it by copying the files to c:\windows\system32,and execuating as your suggestion.But my monitor is 1920x1080,and the "<string>0x0a260006</string>" of “<key>Graphics</key> ” in config.plist doesn't fit my monitor,so I struck in a blurred screen.And I fix it by replacing the "<string>0x0a260006</string>" with "<string>0x0600260a</string>",but I couldn't follow the graphics-accelerated tips you put in "Post Installation".Could you help me with that?

**Comment by ghost** [comment]
Hi Austin SMU,
I build the usb installer with osx 10.10 again and use  the patch of DSDT/SSDT you updated . and run the patch steps of  the m3800.sh script. 
It  boot into a full graphics accelerated desktop WITHOUT QE/CI enabled  and no sound support .
and i download MacPois0n Yosemite v2.9 .pkg and install the  4600  and alc668 drivers  and reboot 
. Finally , It boot with QE/CI enabled and sound enabled .
I buy  an usb wifi card with  chipset MediaTek  MT7601 . It worked perfect .

Thank you for your patience..
